dataset:
  data_path: /project/mira/dataset/MovieNet
  # anno_path: /mnt/ssd2/TropeVLM/tropes/trope_bc_with_definition_subset_5_plot_20_trope.json
  anno_path: /mnt/ssd2/TropeVLM/tropes/trope_bc_with_definition_has_trope.json
  dataset_name: TiMoSBC
  version: multiplechoice
  fps: 10
  max_num_frames: 1
  split: val
  batch_size: 16
  # max_samples: 1
  start_sample: 0
  result_path: /mnt/ssd2/TropeVLM/ViperGPT/results/timos_bc/val/api_pool_test.csv

codex:
  # prompt: ./prompts/benchmarks/timos_bc.prompt
  api_prompt: ./prompts/benchmarks/timos/api.prompt
  function_signature_prompt: ./prompts/benchmarks/timos/function_signature.prompt
  function_format_prompt: ./prompts/benchmarks/timos/function_format.prompt
  example_prompt: [
    ./prompts/benchmarks/timos/codegen_example_1.prompt,
    ./prompts/benchmarks/timos/codegen_example_2.prompt,
    ./prompts/benchmarks/timos/codegen_example_3.prompt,
    ./prompts/benchmarks/timos/codegen_example_4.prompt,
    ./prompts/benchmarks/timos/codegen_example_5.prompt,
  ]
  prototype_prompt: ./prompts/benchmarks/timos/prototype.prompt
  reflection_example_prompt: [
   ./prompts/benchmarks/timos/simple_reflection_example_1.prompt,
  ]
  revised_function_format_prompt: ./prompts/benchmarks/timos/revised_function_format.prompt
  request_example_prompt: [
    ./prompts/benchmarks/timos/request_example_1.prompt,
    ./prompts/benchmarks/timos/request_example_2.prompt,
  ]

select_answer_prompt: ./prompts/gpt3/timos_bc_question_reason.txt
fixed_code_file: ./prompts/fixed_code/blip2_video.prompt

results_dir: ./results/timos_bc/

gpt3:
  model: gpt-3.5-turbo-16k

num_reflections: 1