dataset:
  data_path: /project/mira/dataset/MovieNet
  anno_path: ../tropes/subset_5_plot/trope_bc_with_definition_subset_ozthegreatandpowerful_20_trope.json
  dataset_name: TiMoSBC
  version: multiplechoice
  fps: 10
  # max_num_frames: 1
  split: val
  batch_size: 10
  # max_samples: 1
  start_sample: 0

codex:
  # prompt: ./prompts/benchmarks/timos_bc.prompt
  api_prompt: ./prompts/benchmarks/timos/api.prompt
  example_prompt: [
    ./prompts/benchmarks/timos/codegen_example_1.prompt,
    ./prompts/benchmarks/timos/codegen_example_2.prompt,
    ./prompts/benchmarks/timos/codegen_example_3.prompt,
  ]
  prototype_prompt: ./prompts/benchmarks/timos/prototype.prompt
  reflection_example_prompt: [
   ./prompts/benchmarks/timos/reflection_example_2.prompt,
  ]

select_answer_prompt: ./prompts/gpt3/timos_bc_question.txt
fixed_code_file: ./prompts/fixed_code/blip2_video.prompt

results_dir: ./results/timos_bc/ozthegreat

gpt3:
  model: gpt-3.5-turbo-1106
